version: '3.7'

services:
    db:
        image: mysql:8.0.19
        volumes: 
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dawid
            MYSQL_DATABASE: bazka
            MYSQL_USER: dawid
            MYSQL_PASSWORD: dawid
       
    wordpress:
        depends_on:
            - db
        image: wordpress:5.4.0-php7.4-apache
        ports:
              - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: dawid
            WORDPRESS_DB_PASSWORD: dawid
            WORDPRESS_DB_NAME: bazka
volumes:
    db_data: {}